In [44]:
import numpy as np
list_ = [ 1,2,3,4,5 ]
array_list = np.array(object = list_)

In [45]:
array_list

array([1, 2, 3, 4, 5])

In [46]:
#Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#to print the data types of both the variables.

""" list_ varible is a normal list that may contains sevral kind of different data types while arry_list
is a n dimentional array that contains only same kind of data"""

type(list_)



list

In [47]:
type(array_list)

numpy.ndarray

In [48]:
#Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [49]:
for i in list_: 
    print(type(list_))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


In [50]:
for i in array_list:
    print(type(array_list))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [51]:
#Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [52]:
#Will there be any difference in the data type of the elements present in both the variables, list_ and
#arra_list? If so then print the data types of each and every element present in both the variables, list_
#and arra_list.


for i in list_: 
    print(type(list_))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


In [53]:
for i in array_list: 
    print(type(array_list))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [54]:
#Consider the below code to answer further questions:

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#Q4. Write a code to find the following characteristics of variable, num_array:
#(i) shape
#(ii) size

In [55]:
num_array.shape

(2, 3)

In [56]:
num_array.size

6

In [57]:
#Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

zero_matrix = np.zeros((3,3))

In [58]:
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
#Q6. Create an identity matrix of shape (5,5) using numpy functions?

identity_matrix = np.eye(5,5)

In [60]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])